#pair of keys and value - isme hum vo chizze dete hain jo hmari baar baar use honi hai
seleniumGrid=true
gridURL=http://localhost:4444/wd/hub

#Application URl
url_base = https://opensource-demo.orangehrmlive.com/
url_local = http://localhost/orangehrm/orangehrm-5.8/web/index.php/auth/login
url_grid = http://host.docker.internal/orangehrm/orangehrm-5.8/web/index.php/auth/login

#Browser Configuration
browser = chrome

#credentials 
username = ishan.dhiman02
password = Ishan@1234

#ImplicitWait (in seconds)
implicitWait = 10

#ExplicitWait (in seconds)
explicitWait = 30